### ISSUE TITLE
version error when using BiocGenerics in shinyapps.io deployment

### ISSUE THREAD

**Issue by matt-sd-watson** [Bioconductor/BiocGenerics#14]
I have started to receive the following error with my automatic deployment script to shinyapps: 

![Screenshot from 2022-11-30 10-50-54](https://user-images.githubusercontent.com/40243147/204844769-897c2d35-cc33-4a64-86d8-2a792b241d40.png)

I am using R version 4.2.1, which has remained consistent for my previous deployments. Based on the Bioconductor version being used (3.16), it should be able to download the correct version using Github Actions.

**Comment by hpages** [comment]
I'm not sure how you expect us to help you with this. This is clearly a problem with your automatic deployment script to shinyapps but you provide zero detail on what this script does, how it works. In particular you're not showing what commands the script uses to install Bioconductor packages.

So this is very _very_ unlikely to be a problem with the **BiocGenerics** package itself. Thousands of users have managed to install this package without any problem since the release of BioC 3.16 one month ago. Of course they use `BiocManager::install()` to install all their R packages, because that's the only tool that is guaranteed to work properly. It's also the only installation method that we control and support. See https://bioconductor.org/install/

Best,
H.
