### ISSUE TITLE
which() generic conflicts with that from Matrix 

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocGenerics#3]
Consider the following:

```r
library(BiocGenerics)
which # says it's defined in BiocGenerics

library(Matrix)
which # says it's defined in base
```

This has the following consequences:

```r
library(GenomicRanges)
example(GRanges, echo=FALSE)
which(seqnames(gr) %in% "chr2") # all is well

library(Matrix)
which(seqnames(gr) %in% "chr2")
## Error in which(seqnames(gr) %in% "chr2") :
##   argument to 'which' is not logical
```

Not sure what the best solution is but at worst we could just use the **Matrix** version of the generic.

<details>
<summary>Session information</summary>

```
R Under development (unstable) (2020-02-18 r77829)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /Users/luna/Software/R/trunk/lib/libRblas.dylib
LAPACK: /Users/luna/Software/R/trunk/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
[1] Matrix_1.2-18        GenomicRanges_1.39.2 GenomeInfoDb_1.23.13
[4] IRanges_2.21.3       S4Vectors_0.25.12    BiocGenerics_0.33.0

loaded via a namespace (and not attached):
[1] zlibbioc_1.33.1        compiler_4.0.0         tools_4.0.0
[4] XVector_0.27.0         GenomeInfoDbData_1.2.2 RCurl_1.98-1.1
[7] grid_4.0.0             bitops_1.0-6           lattice_0.20-40
```
</details>

**Comment by LTLA** [comment]
Any thoughts on this? Just ran into this again in another context:

```r
library(Matrix)
y <- rsparsematrix(100, 10, 0.1)
nonzero <- Matrix::which(y > 0) # ok.

library(TENxPBMCData)
sce <- TENxPBMCData("pbmc3k")
nonzero <- Matrix::which(counts(sce) > 0) # fails
```

It's fine if the second `which` is taken from **BiocGenerics**, but my package code needs to use one or the other, and using `BiocGenerics::which` fails for the sparse case.

**Comment by hpages** [comment]
I ran into a similar issue today in DelayedArray.

@lawremi Michael what do you think we should do? I see you added the `which()` generic to BiocGenerics in 2016 (commit 860cce0ec85b94ebca190802be95e61c4f469d6b). With the following comment in the source (`R/which.R` file):
```
    ### We add the ... argument to the generic
    ### functions defined here so they can be called with an arbitrary
    ### number of effective arguments. This was motivated by the desire to
    ### optionally return global subscripts from methods on List.
```
Do we actually use this feature? 

I also see this comment:
```
    ### These generics are slated to be internalized in base R. When that
    ### happens, these calls will effectively be no-ops.
```

Do we have a timeline for this?

Thanks!

**Comment by hpages** [comment]
A dirty workaround is to use "cascading generics" i.e. have the default method for the generic in BiocGenerics point to the generic in Matrix. This works but at the cost of having BiocGenerics depend on Matrix. Also it produces an ugly warning at installation time:
```
hpages@spectre:~$ R CMD INSTALL BiocGenerics
* installing to library ‘/home/hpages/R/R-4.0.r78316/library’
...
** testing if installed package can be loaded from temporary location
Warning: multiple methods tables found for ‘which’
** testing if installed package can be loaded from final location
Warning: multiple methods tables found for ‘which’
** testing if installed package keeps a record of temporary installation path
* DONE (BiocGenerics)
```

Another way to go is that instead of defining a new generic in BiocGenerics we just import it from Matrix and re-export it. That would avoid the warning but we would loose the ellipsis (it doesn't seem that any of the `which()` methods currently defined in Bioconductor needs the ellipsis anyway).

Thoughts?

**Comment by lawremi** [comment]
Currently only `which.min()` and `which.max()` use the ellipsis, in order to add a `global=` argument. That's useful when quickly finding the mode of a many distributions in a vectorized way. HelloRanges uses that to implement `distmode()` in support of its implementation of bedtool's `merge` utility. We should probably elevate `distmode()` and its methods to the core packages and have them call a lower level function to get the global coordinates, so that we do need to add the ellipsis at the top level. Or just drop the optimization. Others might be using that feature though.

For `which()` though we can just drop the ellipsis. Then, the methods package might end up using the same methods table for both generics. Not sure.

**Comment by hpages** [comment]
Done (commit 69e6fad3792d19383e0782ef7a3bf70658bb7159). Also had to drop restriction of dispatch to the first argument in order to get rid of the "multiple methods tables" warning.
